<?php

return array (
  0 => 
  array (
    'id' => 1,
    'order_id' => 1,
    'seller_id' => 9,
    'product_id' => 1,
    'variation' => 'AliceBlue-S',
    'price' => 120.0,
    'tax' => 0.0,
    'shipping_cost' => 0.0,
    'quantity' => 1,
    'payment_status' => 'unpaid',
    'delivery_status' => 'pending',
    'shipping_type' => 'home_delivery',
    'pickup_point_id' => NULL,
    'product_referral_code' => NULL,
    'earn_point' => 0.0,
    'created_at' => '2022-11-03 11:44:54',
    'updated_at' => '2022-11-03 11:44:54',
  ),
  1 => 
  array (
    'id' => 2,
    'order_id' => 2,
    'seller_id' => 9,
    'product_id' => 1,
    'variation' => 'AliceBlue-S',
    'price' => 120.0,
    'tax' => 0.0,
    'shipping_cost' => 0.0,
    'quantity' => 1,
    'payment_status' => 'unpaid',
    'delivery_status' => 'pending',
    'shipping_type' => 'home_delivery',
    'pickup_point_id' => NULL,
    'product_referral_code' => NULL,
    'earn_point' => 0.0,
    'created_at' => '2022-11-03 11:48:17',
    'updated_at' => '2022-11-03 11:48:17',
  ),
  2 => 
  array (
    'id' => 3,
    'order_id' => 3,
    'seller_id' => 9,
    'product_id' => 1,
    'variation' => 'AliceBlue-S',
    'price' => 120.0,
    'tax' => 0.0,
    'shipping_cost' => 0.0,
    'quantity' => 1,
    'payment_status' => 'unpaid',
    'delivery_status' => 'pending',
    'shipping_type' => 'home_delivery',
    'pickup_point_id' => NULL,
    'product_referral_code' => NULL,
    'earn_point' => 0.0,
    'created_at' => '2022-11-03 11:48:38',
    'updated_at' => '2022-11-03 11:48:38',
  ),
  3 => 
  array (
    'id' => 4,
    'order_id' => 4,
    'seller_id' => 9,
    'product_id' => 1,
    'variation' => 'AliceBlue-S',
    'price' => 120.0,
    'tax' => 0.0,
    'shipping_cost' => 0.0,
    'quantity' => 1,
    'payment_status' => 'unpaid',
    'delivery_status' => 'pending',
    'shipping_type' => 'home_delivery',
    'pickup_point_id' => NULL,
    'product_referral_code' => NULL,
    'earn_point' => 0.0,
    'created_at' => '2022-11-03 11:50:55',
    'updated_at' => '2022-11-03 11:50:55',
  ),
  4 => 
  array (
    'id' => 5,
    'order_id' => 5,
    'seller_id' => 9,
    'product_id' => 1,
    'variation' => 'AliceBlue-S',
    'price' => 240.0,
    'tax' => 0.0,
    'shipping_cost' => 0.0,
    'quantity' => 2,
    'payment_status' => 'unpaid',
    'delivery_status' => 'pending',
    'shipping_type' => 'home_delivery',
    'pickup_point_id' => NULL,
    'product_referral_code' => NULL,
    'earn_point' => 0.0,
    'created_at' => '2022-11-03 11:52:11',
    'updated_at' => '2022-11-03 11:52:11',
  ),
  5 => 
  array (
    'id' => 6,
    'order_id' => 6,
    'seller_id' => 9,
    'product_id' => 1,
    'variation' => 'AliceBlue-S',
    'price' => 120.0,
    'tax' => 0.0,
    'shipping_cost' => 0.0,
    'quantity' => 1,
    'payment_status' => 'unpaid',
    'delivery_status' => 'pending',
    'shipping_type' => 'home_delivery',
    'pickup_point_id' => NULL,
    'product_referral_code' => NULL,
    'earn_point' => 0.0,
    'created_at' => '2022-11-03 11:55:15',
    'updated_at' => '2022-11-03 11:55:15',
  ),
  6 => 
  array (
    'id' => 8,
    'order_id' => 8,
    'seller_id' => 9,
    'product_id' => 1,
    'variation' => 'AliceBlue-S',
    'price' => 240.0,
    'tax' => 0.0,
    'shipping_cost' => 0.0,
    'quantity' => 2,
    'payment_status' => 'unpaid',
    'delivery_status' => 'pending',
    'shipping_type' => 'home_delivery',
    'pickup_point_id' => NULL,
    'product_referral_code' => NULL,
    'earn_point' => 0.0,
    'created_at' => '2022-11-03 11:58:18',
    'updated_at' => '2022-11-03 11:58:18',
  ),
  7 => 
  array (
    'id' => 9,
    'order_id' => 9,
    'seller_id' => 9,
    'product_id' => 1,
    'variation' => 'Amethyst-S',
    'price' => 240.0,
    'tax' => 0.0,
    'shipping_cost' => 0.0,
    'quantity' => 2,
    'payment_status' => 'unpaid',
    'delivery_status' => 'pending',
    'shipping_type' => 'home_delivery',
    'pickup_point_id' => NULL,
    'product_referral_code' => NULL,
    'earn_point' => 0.0,
    'created_at' => '2022-11-03 12:07:30',
    'updated_at' => '2022-11-03 12:07:30',
  ),
  8 => 
  array (
    'id' => 10,
    'order_id' => 10,
    'seller_id' => 9,
    'product_id' => 1,
    'variation' => 'AliceBlue-S',
    'price' => 120.0,
    'tax' => 0.0,
    'shipping_cost' => 0.0,
    'quantity' => 1,
    'payment_status' => 'unpaid',
    'delivery_status' => 'pending',
    'shipping_type' => 'home_delivery',
    'pickup_point_id' => NULL,
    'product_referral_code' => NULL,
    'earn_point' => 0.0,
    'created_at' => '2022-11-03 12:50:55',
    'updated_at' => '2022-11-03 12:50:55',
  ),
  9 => 
  array (
    'id' => 12,
    'order_id' => 12,
    'seller_id' => 9,
    'product_id' => 1,
    'variation' => 'AliceBlue-S',
    'price' => 120.0,
    'tax' => 0.0,
    'shipping_cost' => 0.0,
    'quantity' => 1,
    'payment_status' => 'paid',
    'delivery_status' => 'confirmed',
    'shipping_type' => 'home_delivery',
    'pickup_point_id' => NULL,
    'product_referral_code' => NULL,
    'earn_point' => 0.0,
    'created_at' => '2022-11-03 12:51:54',
    'updated_at' => '2022-11-30 04:22:30',
  ),
  10 => 
  array (
    'id' => 13,
    'order_id' => 13,
    'seller_id' => 9,
    'product_id' => 1,
    'variation' => 'AliceBlue-S',
    'price' => 120.0,
    'tax' => 0.0,
    'shipping_cost' => 0.0,
    'quantity' => 1,
    'payment_status' => 'paid',
    'delivery_status' => 'confirmed',
    'shipping_type' => 'home_delivery',
    'pickup_point_id' => NULL,
    'product_referral_code' => NULL,
    'earn_point' => 0.0,
    'created_at' => '2022-11-03 12:54:39',
    'updated_at' => '2022-11-30 04:22:48',
  ),
  11 => 
  array (
    'id' => 15,
    'order_id' => 15,
    'seller_id' => 28,
    'product_id' => 33,
    'variation' => '',
    'price' => 1100.0,
    'tax' => 0.0,
    'shipping_cost' => 0.0,
    'quantity' => 2,
    'payment_status' => 'paid',
    'delivery_status' => 'delivered',
    'shipping_type' => 'home_delivery',
    'pickup_point_id' => NULL,
    'product_referral_code' => NULL,
    'earn_point' => 0.0,
    'created_at' => '2023-02-22 17:34:42',
    'updated_at' => '2023-02-22 17:38:40',
  ),
  12 => 
  array (
    'id' => 16,
    'order_id' => 16,
    'seller_id' => 9,
    'product_id' => 21,
    'variation' => '',
    'price' => 329.0,
    'tax' => 0.0,
    'shipping_cost' => 0.0,
    'quantity' => 1,
    'payment_status' => 'paid',
    'delivery_status' => 'delivered',
    'shipping_type' => NULL,
    'pickup_point_id' => NULL,
    'product_referral_code' => NULL,
    'earn_point' => 0.0,
    'created_at' => '2023-02-23 04:21:03',
    'updated_at' => '2023-06-06 09:46:20',
  ),
  13 => 
  array (
    'id' => 17,
    'order_id' => 17,
    'seller_id' => 9,
    'product_id' => 21,
    'variation' => '',
    'price' => 329.0,
    'tax' => 0.0,
    'shipping_cost' => 0.0,
    'quantity' => 1,
    'payment_status' => 'paid',
    'delivery_status' => 'delivered',
    'shipping_type' => NULL,
    'pickup_point_id' => NULL,
    'product_referral_code' => NULL,
    'earn_point' => 0.0,
    'created_at' => '2023-06-06 09:33:54',
    'updated_at' => '2023-06-06 09:34:27',
  ),
  14 => 
  array (
    'id' => 18,
    'order_id' => 18,
    'seller_id' => 9,
    'product_id' => 24,
    'variation' => '',
    'price' => 133.0,
    'tax' => 0.0,
    'shipping_cost' => 0.0,
    'quantity' => 1,
    'payment_status' => 'paid',
    'delivery_status' => 'pending',
    'shipping_type' => NULL,
    'pickup_point_id' => NULL,
    'product_referral_code' => NULL,
    'earn_point' => 0.0,
    'created_at' => '2026-09-09 12:02:05',
    'updated_at' => '2026-09-09 12:02:05',
  ),
  15 => 
  array (
    'id' => 19,
    'order_id' => 18,
    'seller_id' => 9,
    'product_id' => 20,
    'variation' => '',
    'price' => 499.0,
    'tax' => 0.0,
    'shipping_cost' => 0.0,
    'quantity' => 1,
    'payment_status' => 'paid',
    'delivery_status' => 'pending',
    'shipping_type' => NULL,
    'pickup_point_id' => NULL,
    'product_referral_code' => NULL,
    'earn_point' => 0.0,
    'created_at' => '2026-09-09 12:02:05',
    'updated_at' => '2026-09-09 12:02:05',
  ),
  16 => 
  array (
    'id' => 20,
    'order_id' => 19,
    'seller_id' => 29,
    'product_id' => 34,
    'variation' => '',
    'price' => 1560.0,
    'tax' => 0.0,
    'shipping_cost' => 0.0,
    'quantity' => 2,
    'payment_status' => 'paid',
    'delivery_status' => 'delivered',
    'shipping_type' => 'home_delivery',
    'pickup_point_id' => NULL,
    'product_referral_code' => NULL,
    'earn_point' => 0.0,
    'created_at' => '2026-09-16 08:50:41',
    'updated_at' => '2026-09-16 10:58:28',
  ),
  17 => 
  array (
    'id' => 21,
    'order_id' => 20,
    'seller_id' => 9,
    'product_id' => 20,
    'variation' => '',
    'price' => 499.0,
    'tax' => 0.0,
    'shipping_cost' => 0.0,
    'quantity' => 1,
    'payment_status' => 'paid',
    'delivery_status' => 'pending',
    'shipping_type' => NULL,
    'pickup_point_id' => NULL,
    'product_referral_code' => NULL,
    'earn_point' => 0.0,
    'created_at' => '2026-09-17 10:51:34',
    'updated_at' => '2026-09-17 10:51:34',
  ),
  18 => 
  array (
    'id' => 22,
    'order_id' => 20,
    'seller_id' => 9,
    'product_id' => 24,
    'variation' => '',
    'price' => 133.0,
    'tax' => 0.0,
    'shipping_cost' => 0.0,
    'quantity' => 1,
    'payment_status' => 'paid',
    'delivery_status' => 'pending',
    'shipping_type' => NULL,
    'pickup_point_id' => NULL,
    'product_referral_code' => NULL,
    'earn_point' => 0.0,
    'created_at' => '2026-09-17 10:51:34',
    'updated_at' => '2026-09-17 10:51:34',
  ),
  19 => 
  array (
    'id' => 23,
    'order_id' => 20,
    'seller_id' => 9,
    'product_id' => 13,
    'variation' => '',
    'price' => 269.0,
    'tax' => 0.0,
    'shipping_cost' => 0.0,
    'quantity' => 1,
    'payment_status' => 'paid',
    'delivery_status' => 'pending',
    'shipping_type' => NULL,
    'pickup_point_id' => NULL,
    'product_referral_code' => NULL,
    'earn_point' => 0.0,
    'created_at' => '2026-09-17 10:51:34',
    'updated_at' => '2026-09-17 10:51:34',
  ),
  20 => 
  array (
    'id' => 24,
    'order_id' => 21,
    'seller_id' => 9,
    'product_id' => 7,
    'variation' => '',
    'price' => -6.27,
    'tax' => 0.0,
    'shipping_cost' => 0.0,
    'quantity' => 1,
    'payment_status' => 'unpaid',
    'delivery_status' => 'pending',
    'shipping_type' => NULL,
    'pickup_point_id' => NULL,
    'product_referral_code' => NULL,
    'earn_point' => 0.0,
    'created_at' => '2026-09-17 11:07:29',
    'updated_at' => '2026-09-17 11:07:29',
  ),
  21 => 
  array (
    'id' => 25,
    'order_id' => 21,
    'seller_id' => 9,
    'product_id' => 6,
    'variation' => '',
    'price' => 900.0,
    'tax' => 0.0,
    'shipping_cost' => 0.0,
    'quantity' => 1,
    'payment_status' => 'unpaid',
    'delivery_status' => 'pending',
    'shipping_type' => NULL,
    'pickup_point_id' => NULL,
    'product_referral_code' => NULL,
    'earn_point' => 0.0,
    'created_at' => '2026-09-17 11:07:29',
    'updated_at' => '2026-09-17 11:07:29',
  ),
  22 => 
  array (
    'id' => 26,
    'order_id' => 22,
    'seller_id' => 24,
    'product_id' => 28,
    'variation' => '',
    'price' => 1000.0,
    'tax' => 0.0,
    'shipping_cost' => 0.0,
    'quantity' => 1,
    'payment_status' => 'unpaid',
    'delivery_status' => 'pending',
    'shipping_type' => 'home_delivery',
    'pickup_point_id' => NULL,
    'product_referral_code' => NULL,
    'earn_point' => 0.0,
    'created_at' => '2026-09-17 11:09:14',
    'updated_at' => '2026-09-17 11:09:14',
  ),
  23 => 
  array (
    'id' => 27,
    'order_id' => 23,
    'seller_id' => 24,
    'product_id' => 28,
    'variation' => '',
    'price' => 1000.0,
    'tax' => 0.0,
    'shipping_cost' => 0.0,
    'quantity' => 1,
    'payment_status' => 'unpaid',
    'delivery_status' => 'pending',
    'shipping_type' => 'home_delivery',
    'pickup_point_id' => NULL,
    'product_referral_code' => NULL,
    'earn_point' => 0.0,
    'created_at' => '2026-09-17 11:09:52',
    'updated_at' => '2026-09-17 11:09:52',
  ),
  24 => 
  array (
    'id' => 28,
    'order_id' => 24,
    'seller_id' => 24,
    'product_id' => 28,
    'variation' => '',
    'price' => 1000.0,
    'tax' => 0.0,
    'shipping_cost' => 0.0,
    'quantity' => 1,
    'payment_status' => 'unpaid',
    'delivery_status' => 'pending',
    'shipping_type' => 'home_delivery',
    'pickup_point_id' => NULL,
    'product_referral_code' => NULL,
    'earn_point' => 0.0,
    'created_at' => '2026-09-17 11:10:12',
    'updated_at' => '2026-09-17 11:10:12',
  ),
  25 => 
  array (
    'id' => 29,
    'order_id' => 25,
    'seller_id' => 24,
    'product_id' => 28,
    'variation' => '',
    'price' => 1000.0,
    'tax' => 0.0,
    'shipping_cost' => 0.0,
    'quantity' => 1,
    'payment_status' => 'unpaid',
    'delivery_status' => 'pending',
    'shipping_type' => 'home_delivery',
    'pickup_point_id' => NULL,
    'product_referral_code' => NULL,
    'earn_point' => 0.0,
    'created_at' => '2026-09-17 11:10:30',
    'updated_at' => '2026-09-17 11:10:30',
  ),
  26 => 
  array (
    'id' => 30,
    'order_id' => 26,
    'seller_id' => 9,
    'product_id' => 12,
    'variation' => '',
    'price' => 650.0,
    'tax' => 0.0,
    'shipping_cost' => 30.0,
    'quantity' => 1,
    'payment_status' => 'paid',
    'delivery_status' => 'pending',
    'shipping_type' => NULL,
    'pickup_point_id' => NULL,
    'product_referral_code' => NULL,
    'earn_point' => 0.0,
    'created_at' => '2026-09-19 05:42:49',
    'updated_at' => '2026-09-19 05:42:49',
  ),
  27 => 
  array (
    'id' => 31,
    'order_id' => 26,
    'seller_id' => 9,
    'product_id' => 20,
    'variation' => '',
    'price' => 499.0,
    'tax' => 0.0,
    'shipping_cost' => 30.0,
    'quantity' => 1,
    'payment_status' => 'paid',
    'delivery_status' => 'pending',
    'shipping_type' => NULL,
    'pickup_point_id' => NULL,
    'product_referral_code' => NULL,
    'earn_point' => 0.0,
    'created_at' => '2026-09-19 05:42:49',
    'updated_at' => '2026-09-19 05:42:49',
  ),
  28 => 
  array (
    'id' => 32,
    'order_id' => 27,
    'seller_id' => 9,
    'product_id' => 3,
    'variation' => '',
    'price' => 300.0,
    'tax' => 0.0,
    'shipping_cost' => 0.0,
    'quantity' => 1,
    'payment_status' => 'paid',
    'delivery_status' => 'pending',
    'shipping_type' => NULL,
    'pickup_point_id' => NULL,
    'product_referral_code' => NULL,
    'earn_point' => 0.0,
    'created_at' => '2026-09-19 05:58:22',
    'updated_at' => '2026-09-19 05:58:22',
  ),
  29 => 
  array (
    'id' => 35,
    'order_id' => 30,
    'seller_id' => 9,
    'product_id' => 3,
    'variation' => '',
    'price' => 300.0,
    'tax' => 0.0,
    'shipping_cost' => 0.0,
    'quantity' => 1,
    'payment_status' => 'paid',
    'delivery_status' => 'pending',
    'shipping_type' => NULL,
    'pickup_point_id' => NULL,
    'product_referral_code' => NULL,
    'earn_point' => 0.0,
    'created_at' => '2026-09-19 05:59:20',
    'updated_at' => '2026-09-19 05:59:20',
  ),
  30 => 
  array (
    'id' => 36,
    'order_id' => 31,
    'seller_id' => 9,
    'product_id' => 3,
    'variation' => '',
    'price' => 300.0,
    'tax' => 0.0,
    'shipping_cost' => 0.0,
    'quantity' => 1,
    'payment_status' => 'paid',
    'delivery_status' => 'pending',
    'shipping_type' => NULL,
    'pickup_point_id' => NULL,
    'product_referral_code' => NULL,
    'earn_point' => 0.0,
    'created_at' => '2026-09-19 05:59:20',
    'updated_at' => '2026-09-19 05:59:20',
  ),
  31 => 
  array (
    'id' => 37,
    'order_id' => 32,
    'seller_id' => 9,
    'product_id' => 17,
    'variation' => '',
    'price' => 395.0,
    'tax' => 0.0,
    'shipping_cost' => 0.0,
    'quantity' => 1,
    'payment_status' => 'paid',
    'delivery_status' => 'pending',
    'shipping_type' => NULL,
    'pickup_point_id' => NULL,
    'product_referral_code' => NULL,
    'earn_point' => 0.0,
    'created_at' => '2026-09-19 06:04:36',
    'updated_at' => '2026-09-19 06:04:36',
  ),
  32 => 
  array (
    'id' => 38,
    'order_id' => 33,
    'seller_id' => 9,
    'product_id' => 19,
    'variation' => '',
    'price' => -946.45,
    'tax' => 0.0,
    'shipping_cost' => 0.0,
    'quantity' => 1,
    'payment_status' => 'paid',
    'delivery_status' => 'pending',
    'shipping_type' => NULL,
    'pickup_point_id' => NULL,
    'product_referral_code' => NULL,
    'earn_point' => 0.0,
    'created_at' => '2026-09-19 06:07:21',
    'updated_at' => '2026-09-19 06:07:21',
  ),
  33 => 
  array (
    'id' => 39,
    'order_id' => 34,
    'seller_id' => 9,
    'product_id' => 3,
    'variation' => '',
    'price' => 300.0,
    'tax' => 0.0,
    'shipping_cost' => 0.0,
    'quantity' => 1,
    'payment_status' => 'paid',
    'delivery_status' => 'pending',
    'shipping_type' => NULL,
    'pickup_point_id' => NULL,
    'product_referral_code' => NULL,
    'earn_point' => 0.0,
    'created_at' => '2026-09-19 06:11:00',
    'updated_at' => '2026-09-19 06:11:00',
  ),
  34 => 
  array (
    'id' => 40,
    'order_id' => 35,
    'seller_id' => 9,
    'product_id' => 3,
    'variation' => '',
    'price' => 300.0,
    'tax' => 0.0,
    'shipping_cost' => 0.0,
    'quantity' => 1,
    'payment_status' => 'paid',
    'delivery_status' => 'pending',
    'shipping_type' => NULL,
    'pickup_point_id' => NULL,
    'product_referral_code' => NULL,
    'earn_point' => 0.0,
    'created_at' => '2026-09-19 06:11:00',
    'updated_at' => '2026-09-19 06:11:00',
  ),
  35 => 
  array (
    'id' => 41,
    'order_id' => 36,
    'seller_id' => 9,
    'product_id' => 20,
    'variation' => '',
    'price' => 499.0,
    'tax' => 0.0,
    'shipping_cost' => 0.0,
    'quantity' => 1,
    'payment_status' => 'paid',
    'delivery_status' => 'pending',
    'shipping_type' => NULL,
    'pickup_point_id' => NULL,
    'product_referral_code' => NULL,
    'earn_point' => 0.0,
    'created_at' => '2026-09-19 06:13:52',
    'updated_at' => '2026-09-19 06:13:52',
  ),
  36 => 
  array (
    'id' => 42,
    'order_id' => 37,
    'seller_id' => 9,
    'product_id' => 3,
    'variation' => '',
    'price' => 300.0,
    'tax' => 0.0,
    'shipping_cost' => 0.0,
    'quantity' => 1,
    'payment_status' => 'paid',
    'delivery_status' => 'pending',
    'shipping_type' => NULL,
    'pickup_point_id' => NULL,
    'product_referral_code' => NULL,
    'earn_point' => 0.0,
    'created_at' => '2026-09-19 06:16:19',
    'updated_at' => '2026-09-19 06:16:19',
  ),
  37 => 
  array (
    'id' => 43,
    'order_id' => 38,
    'seller_id' => 9,
    'product_id' => 3,
    'variation' => '',
    'price' => 300.0,
    'tax' => 0.0,
    'shipping_cost' => 0.0,
    'quantity' => 1,
    'payment_status' => 'paid',
    'delivery_status' => 'pending',
    'shipping_type' => NULL,
    'pickup_point_id' => NULL,
    'product_referral_code' => NULL,
    'earn_point' => 0.0,
    'created_at' => '2026-09-19 06:16:19',
    'updated_at' => '2026-09-19 06:16:19',
  ),
  38 => 
  array (
    'id' => 44,
    'order_id' => 39,
    'seller_id' => 9,
    'product_id' => 3,
    'variation' => '',
    'price' => 300.0,
    'tax' => 0.0,
    'shipping_cost' => 0.0,
    'quantity' => 1,
    'payment_status' => 'paid',
    'delivery_status' => 'pending',
    'shipping_type' => NULL,
    'pickup_point_id' => NULL,
    'product_referral_code' => NULL,
    'earn_point' => 0.0,
    'created_at' => '2026-09-19 07:20:20',
    'updated_at' => '2026-09-19 07:20:20',
  ),
  39 => 
  array (
    'id' => 45,
    'order_id' => 40,
    'seller_id' => 9,
    'product_id' => 3,
    'variation' => '',
    'price' => 300.0,
    'tax' => 0.0,
    'shipping_cost' => 0.0,
    'quantity' => 1,
    'payment_status' => 'paid',
    'delivery_status' => 'pending',
    'shipping_type' => NULL,
    'pickup_point_id' => NULL,
    'product_referral_code' => NULL,
    'earn_point' => 0.0,
    'created_at' => '2026-09-19 07:20:20',
    'updated_at' => '2026-09-19 07:20:20',
  ),
  40 => 
  array (
    'id' => 46,
    'order_id' => 41,
    'seller_id' => 9,
    'product_id' => 17,
    'variation' => '',
    'price' => 395.0,
    'tax' => 0.0,
    'shipping_cost' => 0.0,
    'quantity' => 1,
    'payment_status' => 'paid',
    'delivery_status' => 'pending',
    'shipping_type' => NULL,
    'pickup_point_id' => NULL,
    'product_referral_code' => NULL,
    'earn_point' => 0.0,
    'created_at' => '2026-09-19 07:22:12',
    'updated_at' => '2026-09-19 07:22:12',
  ),
  41 => 
  array (
    'id' => 47,
    'order_id' => 42,
    'seller_id' => 9,
    'product_id' => 3,
    'variation' => '',
    'price' => 300.0,
    'tax' => 0.0,
    'shipping_cost' => 0.0,
    'quantity' => 1,
    'payment_status' => 'paid',
    'delivery_status' => 'pending',
    'shipping_type' => NULL,
    'pickup_point_id' => NULL,
    'product_referral_code' => NULL,
    'earn_point' => 0.0,
    'created_at' => '2026-09-19 07:26:13',
    'updated_at' => '2026-09-19 07:26:13',
  ),
  42 => 
  array (
    'id' => 48,
    'order_id' => 43,
    'seller_id' => 9,
    'product_id' => 3,
    'variation' => '',
    'price' => 300.0,
    'tax' => 0.0,
    'shipping_cost' => 0.0,
    'quantity' => 1,
    'payment_status' => 'paid',
    'delivery_status' => 'pending',
    'shipping_type' => NULL,
    'pickup_point_id' => NULL,
    'product_referral_code' => NULL,
    'earn_point' => 0.0,
    'created_at' => '2026-09-19 07:26:13',
    'updated_at' => '2026-09-19 07:26:13',
  ),
  43 => 
  array (
    'id' => 49,
    'order_id' => 44,
    'seller_id' => 9,
    'product_id' => 3,
    'variation' => '',
    'price' => 300.0,
    'tax' => 0.0,
    'shipping_cost' => 0.0,
    'quantity' => 1,
    'payment_status' => 'paid',
    'delivery_status' => 'pending',
    'shipping_type' => NULL,
    'pickup_point_id' => NULL,
    'product_referral_code' => NULL,
    'earn_point' => 0.0,
    'created_at' => '2026-09-20 05:20:11',
    'updated_at' => '2026-09-20 05:20:11',
  ),
  44 => 
  array (
    'id' => 50,
    'order_id' => 45,
    'seller_id' => 9,
    'product_id' => 3,
    'variation' => '',
    'price' => 300.0,
    'tax' => 0.0,
    'shipping_cost' => 0.0,
    'quantity' => 1,
    'payment_status' => 'paid',
    'delivery_status' => 'pending',
    'shipping_type' => NULL,
    'pickup_point_id' => NULL,
    'product_referral_code' => NULL,
    'earn_point' => 0.0,
    'created_at' => '2026-09-20 05:20:11',
    'updated_at' => '2026-09-20 05:20:11',
  ),
  45 => 
  array (
    'id' => 51,
    'order_id' => 46,
    'seller_id' => 9,
    'product_id' => 8,
    'variation' => '',
    'price' => 160.0,
    'tax' => 0.0,
    'shipping_cost' => 0.0,
    'quantity' => 1,
    'payment_status' => 'paid',
    'delivery_status' => 'pending',
    'shipping_type' => NULL,
    'pickup_point_id' => NULL,
    'product_referral_code' => NULL,
    'earn_point' => 0.0,
    'created_at' => '2026-09-20 05:20:43',
    'updated_at' => '2026-09-20 05:20:43',
  ),
  46 => 
  array (
    'id' => 52,
    'order_id' => 47,
    'seller_id' => 9,
    'product_id' => 8,
    'variation' => '',
    'price' => 160.0,
    'tax' => 0.0,
    'shipping_cost' => 0.0,
    'quantity' => 1,
    'payment_status' => 'paid',
    'delivery_status' => 'pending',
    'shipping_type' => NULL,
    'pickup_point_id' => NULL,
    'product_referral_code' => NULL,
    'earn_point' => 0.0,
    'created_at' => '2026-09-20 05:20:43',
    'updated_at' => '2026-09-20 05:20:43',
  ),
  47 => 
  array (
    'id' => 53,
    'order_id' => 48,
    'seller_id' => 9,
    'product_id' => 8,
    'variation' => '',
    'price' => 160.0,
    'tax' => 0.0,
    'shipping_cost' => 0.0,
    'quantity' => 1,
    'payment_status' => 'paid',
    'delivery_status' => 'pending',
    'shipping_type' => NULL,
    'pickup_point_id' => NULL,
    'product_referral_code' => NULL,
    'earn_point' => 0.0,
    'created_at' => '2026-09-20 05:34:45',
    'updated_at' => '2026-09-20 05:34:45',
  ),
  48 => 
  array (
    'id' => 54,
    'order_id' => 49,
    'seller_id' => 9,
    'product_id' => 8,
    'variation' => '',
    'price' => 160.0,
    'tax' => 0.0,
    'shipping_cost' => 0.0,
    'quantity' => 1,
    'payment_status' => 'paid',
    'delivery_status' => 'pending',
    'shipping_type' => NULL,
    'pickup_point_id' => NULL,
    'product_referral_code' => NULL,
    'earn_point' => 0.0,
    'created_at' => '2026-09-20 05:34:45',
    'updated_at' => '2026-09-20 05:34:45',
  ),
  49 => 
  array (
    'id' => 55,
    'order_id' => 50,
    'seller_id' => 9,
    'product_id' => 8,
    'variation' => '',
    'price' => 160.0,
    'tax' => 0.0,
    'shipping_cost' => 0.0,
    'quantity' => 1,
    'payment_status' => 'paid',
    'delivery_status' => 'pending',
    'shipping_type' => NULL,
    'pickup_point_id' => NULL,
    'product_referral_code' => NULL,
    'earn_point' => 0.0,
    'created_at' => '2026-09-20 05:42:15',
    'updated_at' => '2026-09-20 05:42:15',
  ),
  50 => 
  array (
    'id' => 56,
    'order_id' => 51,
    'seller_id' => 9,
    'product_id' => 8,
    'variation' => '',
    'price' => 160.0,
    'tax' => 0.0,
    'shipping_cost' => 0.0,
    'quantity' => 1,
    'payment_status' => 'paid',
    'delivery_status' => 'pending',
    'shipping_type' => NULL,
    'pickup_point_id' => NULL,
    'product_referral_code' => NULL,
    'earn_point' => 0.0,
    'created_at' => '2026-09-20 05:42:16',
    'updated_at' => '2026-09-20 05:42:16',
  ),
);
