<?php

use Illuminate\Support\Facades\Hash;

return array (
  0 =>
  array (
    'id' => 8,
    'referred_by' => NULL,
    'provider' => NULL,
    'provider_id' => NULL,
    'refresh_token' => NULL,
    'access_token' => NULL,
    'user_type' => 'customer',
    'name' => 'Mr. Customer',
    'email' => 'customer@example.com',
    'email_verified_at' => '2018-12-11 18:00:00',
    'verification_code' => NULL,
    'new_email_verificiation_code' => NULL,
    'password' => Hash::make('123456'),
    'remember_token' => 'MihqVOGUF6Qnf2vXUUTqcATCwCVJfvPHTXn5gpEvuSLeLdLI9bCuHQB2wfgZ',
    'device_token' => NULL,
    'avatar' => 'https://lh3.googleusercontent.com/-7OnRtLyua5Q/AAAAAAAAAAI/AAAAAAAADRk/VqWKMl4f8CI/photo.jpg?sz=50',
    'avatar_original' => NULL,
    'address' => 'Demo address',
    'country' => 'US',
    'state' => NULL,
    'city' => 'Demo city',
    'postal_code' => '1234',
    'phone' => NULL,
    'balance' => 0.0,
    'banned' => 0,
    'referral_code' => '8zJTyXTlTT',
    'customer_package_id' => NULL,
    'remaining_uploads' => NULL,
    'created_at' => '2018-10-07 04:42:57',
    'updated_at' => '2026-09-17 11:08:15',
  ),
  1 =>
  array (
    'id' => 9,
    'referred_by' => NULL,
    'provider' => NULL,
    'provider_id' => NULL,
    'refresh_token' => NULL,
    'access_token' => NULL,
    'user_type' => 'admin',
    'name' => 'eManager',
    'email' => 'info@emanager.com',
    'email_verified_at' => '2022-11-03 06:11:21',
    'verification_code' => NULL,
    'new_email_verificiation_code' => NULL,
    'password' => Hash::make('emanager'),
    'remember_token' => 'w7gRxUuvZAbk1plKtqpBiQYbAQBdg4fPZsHPO1Dvyi2nxuoByStYlR237LcB',
    'device_token' => NULL,
    'avatar' => NULL,
    'avatar_original' => '99',
    'address' => NULL,
    'country' => NULL,
    'state' => NULL,
    'city' => NULL,
    'postal_code' => NULL,
    'phone' => NULL,
    'balance' => 0.0,
    'banned' => 0,
    'referral_code' => NULL,
    'customer_package_id' => NULL,
    'remaining_uploads' => 0,
    'created_at' => '2022-11-03 06:41:21',
    'updated_at' => '2026-09-17 10:39:56',
  ),
  2 =>
  array (
    'id' => 10,
    'referred_by' => NULL,
    'provider' => NULL,
    'provider_id' => NULL,
    'refresh_token' => NULL,
    'access_token' => NULL,
    'user_type' => 'customer',
    'name' => 'md Sayed',
    'email' => 'sayed75@gmail.com',
    'email_verified_at' => '2022-11-03 07:11:55',
    'verification_code' => '608636',
    'new_email_verificiation_code' => NULL,
    'password' => Hash::make('sayed75'),
    'remember_token' => NULL,
    'device_token' => NULL,
    'avatar' => NULL,
    'avatar_original' => NULL,
    'address' => NULL,
    'country' => NULL,
    'state' => NULL,
    'city' => NULL,
    'postal_code' => NULL,
    'phone' => NULL,
    'balance' => 0.0,
    'banned' => 0,
    'referral_code' => NULL,
    'customer_package_id' => NULL,
    'remaining_uploads' => 0,
    'created_at' => '2022-11-03 07:05:55',
    'updated_at' => '2022-11-03 07:05:55',
  ),
);
